[colors]
background = "#24283bF0"
text_primary = "#c0caf5FF"
text_muted = "#9aa5ceFF"
accent_primary = "#7aa2f7FF"
accent_secondary = "#bb9af7FF"
warning = "#9ece6aFF"
error = "#f7768eFF"

[appearance]
border_focused = "#7aa2f7FF"
border_unfocused = "#24283bFF"
scratchpad_border_focused = "#9ece6aFF"
scratchpad_border_unfocused = "#44691cFF"
outer_border_color = "#1a1b26FF"
insert_hint_color = "#9ece6a80"
backdrop_color = "#24283bFF"

[overview]
background_tint = "#1a1b2688"
